exclude: '^docs/conf.py'

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.1.0
  hooks:
  - id: trailing-whitespace
  - id: check-added-large-files
  - id: check-ast
  - id: check-json
  - id: check-merge-conflict
  - id: check-xml
  - id: check-yaml
  - id: debug-statements
  - id: end-of-file-fixer
    exclude: |
        (?x)(
            environment.yml|
            environment.mac.yml
        )
  - id: requirements-txt-fixer
  - id: mixed-line-ending
    args: ['--fix=no']
    # exclude: environment.yml

# -   repo: https://gitlab.com/pycqa/flake8
#     rev: 3.8.0
#     hooks:
#     -   id: flake8
#         additional_dependencies: [flake8-typing-imports==1.7.0]
#         args: ['--max-line-length=88']  # default of Black

- repo: https://github.com/pre-commit/mirrors-isort
  rev: v5.0.4
  hooks:
  - id: isort
