version: '3.6'
services:

  dev:
    image: hello-world:latest

  load_balancer:
    image: hello-world:latest
    # volumes:
    #   - ${SERVER7_PATH}/app/load_balancer:/app

  app_kcp:
    image: hello-world:latest
    # volumes:
    #   - ${SERVER7_PATH}/app/app_kcp:/app
    #   - ${SERVER7_PATH}/app/app_kcp/site.conf:/etc/nginx/conf.d/site.conf

  app_jdc:
    image: hello-world:latest
    # volumes:
    #   - ${SERVER7_PATH}/app/app_jdc:/app
    #   - ${SERVER7_PATH}/app/app_jdc/site.conf:/etc/nginx/conf.d/site.conf

  dfr:
    image: hello-world:latest
    # # ports:
    # # - "8098:80"
    # volumes:
    #   - ${SERVER7_PATH}/app/dfr/data:/usr/share/nginx/html/data

  mongodb:
    volumes:
      - ${SERVER7_DATA_PATH}/data/mongodb:/data/db
    ports:
      - 127.0.0.1:27020:27017

  milvus:
    volumes:
      - ${SERVER7_DATA_PATH}/milvus/db:/var/lib/milvus/db
      - ${SERVER7_DATA_PATH}/milvus/logs:/var/lib/milvus/logs
      - ${SERVER7_DATA_PATH}/milvus/wal:/var/lib/milvus/wal
      - ${SERVER7_PATH}/milvus/conf:/var/lib/milvus/conf

  es01:
    volumes:
      - ${SERVER7_DATA_PATH}/elasticsearch/data/01:/usr/share/elasticsearch/data
  es02:
    volumes:
      - ${SERVER7_DATA_PATH}/elasticsearch/data/02:/usr/share/elasticsearch/data
  es03:
    volumes:
      - ${SERVER7_DATA_PATH}/elasticsearch/data/03:/usr/share/elasticsearch/data

  nlp_api:
    volumes:
      - ${SERVER7_DATA_PATH}/models:/workspace/models
      - ${SERVER7_DATA_PATH}/data:/workspace/data
      - ${SERVER7_DATA_PATH}/../scrapers:/workspace/scrapers
      - ${SERVER7_PATH}/data/whitelists:/workspace/data/whitelists
      - ${SERVER7_PATH}/data/maps:/workspace/data/maps

      # - ${SERVER7_DATA_PATH}/data/corpus:/workspace/data/corpus
      # - ${SERVER7_DATA_PATH}/data/raw:/workspace/data/raw
      # - ${SERVER7_DATA_PATH}/data/preprocessed:/workspace/data/preprocessed
