version: '3.6'
services:

  dev:
    build:
      context: ./
      dockerfile: .devcontainer/Dockerfile.dev.base
      args:
        USERNAME: vscode
        USER_UID: 1000
        ENV_ID: dev
        ENV_DEV_BASE_FILE: "environment.dev.base.local.yml"
        PROJECT_ID: wb_nlp
        ENV_DEV_FILE: "environment.dev.local.yml"
    volumes:
      - ./:/workspace
    # ports:
    #   - "8000:8000"
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '4'
    #       memory: 4G
    #     reservations:
    #       cpus: '3'
    #       memory: 3G

  tika:
    image: apache/tika:latest

  redis:
    image: redis:latest

  selenium:
    image: selenium/standalone-chrome:4.0.0-alpha-7-prerelease-20200907
    ports:
      - 127.0.0.1:4444:4444
    volumes:
      - /dev/shm:/dev/shm
