version: '3.6'
services:

  dev:
    image: hello-world:latest
  #   build:
  #     context: ./
  #     dockerfile: .devcontainer/Dockerfile.dev.base
  #     args:
  #       USERNAME: vscode
  #       USER_UID: 1000
  #       ENV_ID: dev
  #       ENV_DEV_BASE_FILE: "environment.dev.base.remote.yml"
  #       PROJECT_ID: wb_nlp
  #       ENV_DEV_FILE: "environment.dev.remote.yml"
  #   volumes:
  #     - ${STAGING_PATH}:/workspace
  #     # - ./:/workspace
  #     # - ${STAGING_PATH}:/workspace:cached
  #   # ports:
  #   #   - "8000:8000"
  #   depends_on:
  #     - mongodb
  #     - web

  load_balancer:
    build:
      context: ./app/load_balancer
    restart: always
    ports:
      - "80:80"
    env_file:
      - .env
    volumes:
      - ${STAGING_PATH}/app/load_balancer:/app
      # - ${STAGING_PATH}/app/app_jdc/site.conf:/etc/nginx/conf.d/site.conf
    links:
      - app_kcp
      - app_jdc
    depends_on:
      - app_kcp
      - app_jdc


  app:
    volumes:
      - ${STAGING_PATH}/app/app_vue2:/app
      - ${STAGING_PATH}/app/app_vue2/site.conf:/etc/nginx/conf.d/site.conf

  app_kcp:
    volumes:
      - ${STAGING_PATH}/app/app_kcp:/app
      # - ${STAGING_PATH}/app/app_kcp/site.conf:/etc/nginx/conf.d/site.conf

  app_jdc:
    volumes:
      - ${STAGING_PATH}/app/app_jdc:/app
      # - ${STAGING_PATH}/app/app_jdc/site.conf:/etc/nginx/conf.d/site.conf

  api:
    volumes:
      - ${STAGING_PATH}/models:/workspace/models
      - ${STAGING_PATH}/data/preprocessed:/workspace/data/preprocessed
      - ${STAGING_PATH}/data/whitelists:/workspace/data/whitelists
    # command:
      # - "/opt/conda/envs/prod/bin/gunicorn -w 4 -b 0.0.0.0:8910 --chdir /workspace/app/api server:app  --reload --timeout 1200"
      # - "tail -f /dev/null"
    ports:
      - "8911:8910"
    links:
      - mongodb
    depends_on:
      - mongodb

  dfr:
    ports:
    - "8098:80"
    volumes:
      - ${STAGING_PATH}/app/dfr/data:/usr/share/nginx/html/data

  web:
    ports:
      - "8880:80"
    volumes:
      - ${STAGING_PATH}/app/frontend:/frontend/nlp
      - ${STAGING_PATH}/app/site.conf:/etc/nginx/conf.d/site.conf

  php:
    volumes:
      - ${STAGING_PATH}/app/frontend:/frontend/nlp
      # - ./app/frontend:/frontend/nlp

  mongodb:
    volumes:
      - ${STAGING_PATH}/data/mongodb:/data/db
      # - ./data/mongodb:/data/db
    ports:
      - 27018:27017
  # nlp-app-mongodb:
  #   image: mongo:latest
  #   environment:
  #     - MONGO_DATA_DIR=/data/db
  #     - MONGO_LOG_DIR=/dev/null
  #   volumes:
  #     - $BASE_DIR/$NLP_APP_MONGODB_DATADIR:/data/db
  #   ports:
  #     - $NLP_APP_MONGODB_PORT:27017
  #   # command: mongod --smallfiles  # --auth
  #   env_file:
  #     - .env

  milvus:
    volumes:
      - ${STAGING_PATH}/milvus/db:/var/lib/milvus/db
      - ${STAGING_PATH}/milvus/conf:/var/lib/milvus/conf
      - ${STAGING_PATH}/milvus/logs:/var/lib/milvus/logs
      - ${STAGING_PATH}/milvus/wal:/var/lib/milvus/wal

  es01:
    volumes:
      - ${STAGING_PATH}/elasticsearch/data/01:/usr/share/elasticsearch/data
  es02:
    volumes:
      - ${STAGING_PATH}/elasticsearch/data/02:/usr/share/elasticsearch/data
  es03:
    volumes:
      - ${STAGING_PATH}/elasticsearch/data/03:/usr/share/elasticsearch/data

  nlp_api:
    volumes:
      - ${STAGING_PATH}/models:/workspace/models
      - ${STAGING_PATH}/data:/workspace/data
      # - ${STAGING_PATH}/data/corpus:/workspace/data/corpus
      # - ${STAGING_PATH}/data/raw:/workspace/data/raw
      # - ${STAGING_PATH}/data/preprocessed:/workspace/data/preprocessed
      # - ${STAGING_PATH}/data/whitelists:/workspace/data/whitelists

  app_label:
    volumes:
      - ${STAGING_PATH}/app/app_label:/app
      - ${STAGING_PATH}/app/app_label/site.conf:/etc/nginx/conf.d/site.conf
