version: '3.6'
services:

  base:
    image: dev-container-base
    build:
      context: ./
      dockerfile: .devcontainer/Dockerfile.dev.base
      args:
        buildno: 1
        VARIANT: "3.7"
        PYTHON_PACKAGE: "python3.7  python3-pip python3-venv"
        USERNAME: vscode
        ENV_ID: dev
        ENV_DEV_BASE_FILE: "environment.dev.base.yml"

  dev:
    build:
      context: ./
      dockerfile: .devcontainer/Dockerfile.dev
      args:
        ENV_DEV_FILE: "environment.dev.yml"
        PROJECT_ID: wb_nlp
    volumes:
      - ./:/workspace
    depends_on:
      - base

    # deploy:
    #   resources:
    #     limits:
    #       cpus: '4'
    #       memory: 4G
    #     reservations:
    #       cpus: '3'
    #       memory: 3G

  web:
    image: nginx:latest
    ports:
    - "80:80"
    volumes:
        - ./app/frontend:/frontend/nlp
        - ./app/site.conf:/etc/nginx/conf.d/site.conf
    links:
      - php
    depends_on:
      - php

  php:
    image: php:7-fpm
    volumes:
      - ./app/frontend:/frontend/nlp

  tika:
    image: apache/tika:latest

  # nlp-app-mongodb:
  #   image: mongo:latest
  #   environment:
  #     - MONGO_DATA_DIR=/data/db
  #     - MONGO_LOG_DIR=/dev/null
  #   volumes:
  #     - $BASE_DIR/$NLP_APP_MONGODB_DATADIR:/data/db
  #   ports:
  #     - $NLP_APP_MONGODB_PORT:27017
  #   # command: mongod --smallfiles  # --auth
  #   env_file:
  #     - .env
