version: '3.6'
services:

  dev:
    build:
      context: ./
      dockerfile: .devcontainer/Dockerfile.dev.base
      args:
        USERNAME: vscode
        USER_UID: 1000
        ENV_ID: dev
        ENV_DEV_BASE_FILE: "environment.dev.base.yml"
        PROJECT_ID: wb_nlp
        ENV_DEV_FILE: "environment.dev.yml"
    volumes:
      - ./:/workspace
    links:
      - mongodb
    depends_on:
      - mongodb
    # ports:
    #   - "8000:8000"
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '4'
    #       memory: 4G
    #     reservations:
    #       cpus: '3'
    #       memory: 3G

  api:
    build:
      context: ./
      dockerfile: ./app/api/Dockerfile
      args:
        ENV_ID: prod
        ENV_PROD_FILE: "environment.prod.api.yml"
    volumes:
      - ./models:/workspace/models
      - ./data/preprocessed:/workspace/data/preprocessed
      - ./data/whitelists:/workspace/data/whitelists
    # command:
    #   - /opt/conda/envs/prod/bin/gunicorn -w 4 -b 0.0.0.0:8910 --chdir /workspace/app/api server:app  --reload --timeout 1200
    ports:
      - "8911:8910"
    links:
      - mongodb
    depends_on:
      - mongodb

  app:
    build:
      context: ./app/app_vue2
    ports:
    - "8088:80"
    volumes:
      - ./site.conf:/etc/nginx/conf.d/site.conf
    links:
      - api
    depends_on:
      - api

  dfr:
    build:
      context: ./app/dfr
    ports:
    - "8098:80"
    volumes:
      - ./app/dfr/data:/usr/share/nginx/html/data

  web:
    image: nginx:latest
    ports:
    - "8880:80"
    volumes:
        - ./app/frontend:/frontend/nlp
        - ./app/site.conf:/etc/nginx/conf.d/site.conf
    links:
      - php
      - api
    depends_on:
      - php
      - api

  php:
    image: php:7-fpm
    volumes:
      - ./app/frontend:/frontend/nlp

  tika:
    image: apache/tika:latest

  redis:
    image: redis:latest

  selenium:
    image: selenium/standalone-chrome:4.0.0-alpha-7-prerelease-20200907
    ports:
      - "4444:4444"
    volumes:
      - /dev/shm:/dev/shm

  mongodb:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    # volumes:
    #   - $BASE_DIR/$NLP_APP_MONGODB_DATADIR:/data/db
    # ports:
    #   - $NLP_APP_MONGODB_PORT:27017
    # # command: mongod --smallfiles  # --auth
    # env_file:
    #   - .env
