version: '3.6'
services:

  dev:
    build:
      context: ./
      dockerfile: .devcontainer/Dockerfile.dev.base
      args:
        USERNAME: vscode
        USER_UID: 1000
        ENV_ID: dev
        ENV_DEV_BASE_FILE: "environment.dev.base.remote.yml"
        PROJECT_ID: wb_nlp
        ENV_DEV_FILE: "environment.dev.remote.yml"
    volumes:
      - ${REMOTE_PATH}:/workspace
      - ${REMOTE_PATH}/../scrapers:/workspace/scrapers
      # - ./:/workspace
      # - ${REMOTE_PATH}:/workspace:cached
    # ports:
    #   - "8000:8000"
    depends_on:
      - mongodb

  load_balancer:
    build:
      context: ./app/load_balancer
    restart: always
    ports:
      - "80:80"
    env_file:
      - .env
    volumes:
      - ${REMOTE_PATH}/app/load_balancer:/app
    links:
      - app_kcp
      - app_jdc
    depends_on:
      - app_kcp
      - app_jdc

  app_kcp:
    volumes:
      - ${REMOTE_PATH}/app/app_kcp:/app
      - ${REMOTE_PATH}/app/app_kcp/site.conf:/etc/nginx/conf.d/site.conf

  app_jdc:
    volumes:
      - ${REMOTE_PATH}/app/app_jdc:/app
      - ${REMOTE_PATH}/app/app_jdc/site.conf:/etc/nginx/conf.d/site.conf

  dfr:
    # ports:
    # - "8098:80"
    volumes:
      - ${REMOTE_PATH}/models/dfr/data:/usr/share/nginx/html/data
      # - ${REMOTE_PATH}/app/dfr/data:/usr/share/nginx/html/data

  mongodb:
    volumes:
      - ${REMOTE_PATH}/data/mongodb:/data/db
    ports:
      - 127.0.0.1:27018:27017

  milvus:
    volumes:
      - ${REMOTE_PATH}/milvus/db:/var/lib/milvus/db
      - ${REMOTE_PATH}/milvus/conf:/var/lib/milvus/conf
      - ${REMOTE_PATH}/milvus/logs:/var/lib/milvus/logs
      - ${REMOTE_PATH}/milvus/wal:/var/lib/milvus/wal

  es01:
    volumes:
      - ${REMOTE_PATH}/elasticsearch/data/01:/usr/share/elasticsearch/data
  es02:
    volumes:
      - ${REMOTE_PATH}/elasticsearch/data/02:/usr/share/elasticsearch/data
  es03:
    volumes:
      - ${REMOTE_PATH}/elasticsearch/data/03:/usr/share/elasticsearch/data

  nlp_api:
    volumes:
      - ${REMOTE_PATH}/models:/workspace/models
      - ${REMOTE_PATH}/data:/workspace/data
      # - ${REMOTE_PATH}/data/preprocessed:/workspace/data/preprocessed
      # - ${REMOTE_PATH}/data/whitelists:/workspace/data/whitelists

  selenium:
    environment:
      - JAVA_OPTS=-Dwebdriver.chrome.whitelistedIps=
