version: '3.6'
services:

  dev:
    build:
      context: ./
      dockerfile: .devcontainer/Dockerfile.dev.base
      args:
        USERNAME: vscode
        USER_UID: 1000
        ENV_ID: dev
        ENV_DEV_BASE_FILE: "environment.dev.base.remote.yml"
        PROJECT_ID: wb_nlp
        ENV_DEV_FILE: "environment.dev.remote.yml"
    volumes:
      - /home/avsolatorio/WBG/wb_nlp:/workspace
      # - ./:/workspace
      # - /home/avsolatorio/WBG/wb_nlp:/workspace:cached
    # ports:
    #   - "8000:8000"
    depends_on:
      - mongodb
      - web

  # app:
  #   build:
  #     context: ./app/app_vue2
  #     dockerfile: Dockerfile
  #   volumes:
  #     - /home/avsolatorio/WBG/wb_nlp/app/app_vue2:/app
  #     # - ./:/workspace
  #     # - /home/avsolatorio/WBG/wb_nlp:/workspace:cached
  #   ports:
  #     - "8088:8000"
  #   depends_on:
  #     - web

  api:
    volumes:
      - /home/avsolatorio/WBG/wb_nlp/models:/workspace/models
      - /home/avsolatorio/WBG/wb_nlp/data/preprocessed:/workspace/data/preprocessed
      - /home/avsolatorio/WBG/wb_nlp/data/whitelists:/workspace/data/whitelists
    command:
      - gunicorn -w 4 -b 0.0.0.0:8910 --chdir /workspace/app/api server:app  --reload --timeout 1200
    ports:
      - "8911:8910"
    links:
      - mongodb
    depends_on:
      - mongodb

  app:
    ports:
      - "8088:80"
    volumes:
      - /home/avsolatorio/WBG/wb_nlp/app/app_vue2/site.conf:/etc/nginx/conf.d/site.conf

  dfr:
    ports:
    - "8098:80"
    volumes:
      - /home/avsolatorio/WBG/wb_nlp/app/dfr/data:/usr/share/nginx/html/data

  web:
    ports:
      - "8880:80"
    volumes:
      - /home/avsolatorio/WBG/wb_nlp/app/frontend:/frontend/nlp
      - /home/avsolatorio/WBG/wb_nlp/app/site.conf:/etc/nginx/conf.d/site.conf

  php:
    volumes:
      - /home/avsolatorio/WBG/wb_nlp/app/frontend:/frontend/nlp
      # - ./app/frontend:/frontend/nlp

  mongodb:
    volumes:
      - /home/avsolatorio/WBG/wb_nlp/data/mongodb:/data/db
      # - ./data/mongodb:/data/db
    ports:
      - 27018:27017
  # nlp-app-mongodb:
  #   image: mongo:latest
  #   environment:
  #     - MONGO_DATA_DIR=/data/db
  #     - MONGO_LOG_DIR=/dev/null
  #   volumes:
  #     - $BASE_DIR/$NLP_APP_MONGODB_DATADIR:/data/db
  #   ports:
  #     - $NLP_APP_MONGODB_PORT:27017
  #   # command: mongod --smallfiles  # --auth
  #   env_file:
  #     - .env
