version: '3.6'
services:

  dev:
    image: hello-world:latest

  load_balancer:
    volumes:
      - ${STAGING_PATH}/app/load_balancer:/app

  app_kcp:
    volumes:
      - ${STAGING_PATH}/app/app_kcp:/app

  app_jdc:
    volumes:
      - ${STAGING_PATH}/app/app_jdc:/app

  dfr:
    # ports:
    # - "8098:80"
    volumes:
      - ${STAGING_PATH}/app/dfr/data:/usr/share/nginx/html/data

  mongodb:
    volumes:
      - ${STAGING_PATH}/data/mongodb:/data/db
    ports:
      - 127.0.0.1:27018:27017

  milvus:
    volumes:
      - ${STAGING_PATH}/milvus/db:/var/lib/milvus/db
      - ${STAGING_PATH}/milvus/conf:/var/lib/milvus/conf
      - ${STAGING_PATH}/milvus/logs:/var/lib/milvus/logs
      - ${STAGING_PATH}/milvus/wal:/var/lib/milvus/wal

  es01:
    volumes:
      - ${STAGING_PATH}/elasticsearch/data/01:/usr/share/elasticsearch/data
  es02:
    volumes:
      - ${STAGING_PATH}/elasticsearch/data/02:/usr/share/elasticsearch/data
  es03:
    volumes:
      - ${STAGING_PATH}/elasticsearch/data/03:/usr/share/elasticsearch/data

  nlp_api:
    volumes:
      - ${STAGING_PATH}/models:/workspace/models
      - ${STAGING_PATH}/data:/workspace/data
      # - ${STAGING_PATH}/data/corpus:/workspace/data/corpus
      # - ${STAGING_PATH}/data/raw:/workspace/data/raw
      # - ${STAGING_PATH}/data/preprocessed:/workspace/data/preprocessed
      # - ${STAGING_PATH}/data/whitelists:/workspace/data/whitelists
