version: '3.6'
services:

  dev:
    image: hello-world:latest

  load_balancer:
    build:
      context: ./app/load_balancer
    restart: always
    ports:
      - "80:80"
    env_file:
      - .env
    volumes:
      - ${LOCAL_PATH}/app/load_balancer:/app
    links:
      - app_kcp
      - app_jdc
    depends_on:
      - app_kcp
      - app_jdc

  app_kcp:
    build:
      context: ./app/app_kcp
    restart: always
    # ports:
    #   - 127.0.0.1:8099:80
    env_file:
      - .env
    volumes:
      - ${LOCAL_PATH}/app/app_kcp:/app
      # - ${LOCAL_PATH}/app/app_kcp/site.conf:/etc/nginx/conf.d/site.conf
    links:
      - nlp_api
    depends_on:
      - nlp_api

  app_jdc:
    build:
      context: ./app/app_jdc
    restart: always
    # ports:
    #   - 127.0.0.1:8089:80
    env_file:
      - .env
    volumes:
      - ${LOCAL_PATH}/app/app_jdc:/app
      # - ${LOCAL_PATH}/app/app_jdc/site.conf:/etc/nginx/conf.d/site.conf
    links:
      - nlp_api
    depends_on:
      - nlp_api

  dfr:
    build:
      context: ./app/dfr
    restart: always
    # ports:
    #   - 127.0.0.1:8098:80
    env_file:
      - .env
    volumes:
      - ${LOCAL_PATH}/models/dfr/data:/usr/share/nginx/html/data
      # - ${LOCAL_PATH}/app/dfr/data:/usr/share/nginx/html/data

  tika:
    image: apache/tika:latest
    restart: always

  redis:
    image: redis:latest
    restart: always

  selenium:
    # image: selenium/standalone-chrome:4.0.0-beta-1-prerelease-20210209
    image: selenium/standalone-chrome:88.0
    restart: always
    ports:
      - 127.0.0.1:4444:4444
    volumes:
      - /dev/shm:/dev/shm

  mongodb:
    image: mongo:latest
    restart: always
    env_file:
      - .env
    environment:
      - ${LOCAL_PATH}/data/mongodb:/data/db
    ports:
      - 127.0.0.1:27018:27017

  milvus:
    # image: milvusdb/milvus:cpu-latest
    image: milvusdb/milvus:0.11.0-cpu-d101620-4c44c0
    restart: always
    env_file:
      - .env
    volumes:
      - ${LOCAL_PATH}/milvus/db:/var/lib/milvus/db
      - ${LOCAL_PATH}/milvus/conf:/var/lib/milvus/conf
      - ${LOCAL_PATH}/milvus/logs:/var/lib/milvus/logs
      - ${LOCAL_PATH}/milvus/wal:/var/lib/milvus/wal
    ports:
      - 127.0.0.1:19530:19530
      - 127.0.0.1:19121:19121

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    restart: always
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ${LOCAL_PATH}/elasticsearch/data/01:/usr/share/elasticsearch/data
    ports:
      - 127.0.0.1:9200:9200
    # networks:
    #   - elastic
    #   # - default
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    restart: always
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ${LOCAL_PATH}/elasticsearch/data/02:/usr/share/elasticsearch/data
    # networks:
    #   - elastic
  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    restart: always
    container_name: es03
    environment:
      - node.name=es03
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ${LOCAL_PATH}/elasticsearch/data/03:/usr/share/elasticsearch/data
    # networks:
    #   - elastic

  nlp_api:
    build:
      context: ./
      dockerfile: ./app/nlp_api/Dockerfile
      args:
        ENV_ID: nlp_api
        ENV_PROD_FILE: "environment.nlp_api.yml"
        PORT: 8919
    restart: always
    env_file:
      - .env
    volumes:
      - ${LOCAL_PATH}/models:/workspace/models
      - ${LOCAL_PATH}/data/preprocessed:/workspace/data/preprocessed
      - ${LOCAL_PATH}/data/whitelists:/workspace/data/whitelists
    ports:
      - "8991:8919"
    links:
      - mongodb
      - es01
    depends_on:
      - mongodb
      - es01

# networks:
#   elastic:
#     driver: bridge
