name: dev
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alabaster=0.7.12
  - altair=4.1.0
  - aniso8601=8.0.0
  - appdirs=1.4.3
  - argon2-cffi=20.1.0
  - astroid=2.4.2
  - async_generator=1.10
  - attrs=20.2.0
  - autopep8=1.5.4
  - babel=2.8.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.1
  - bandit=1.6.2
  - beautifulsoup4=4.9.1
  - black=20.8b1
  - bleach=3.2.0
  - bokeh=2.2.1
  - boto=2.49.0
  - boto3=1.14.63
  - botocore=1.17.63
  - brotlipy=0.7.0
  - bs4=4.9.1
  - bz2file=0.98
  - c-ares=1.16.1
  - ca-certificates=2020.6.20
  - cachetools=4.1.1
  - catalogue=1.0.0
  - certifi=2020.6.20
  - cffi=1.14.3
  - cfgv=3.2.0
  - chardet=3.0.4
  - click=7.1.2
  - cloudpickle=1.6.0
  - colorama=0.4.3
  - commonmark=0.9.1
  - coverage=5.3
  - cryptography=3.1
  - cycler=0.10.0
  - cymem=2.0.3
  - cython=0.29.21
  - cython-blis=0.4.1
  - cytoolz=0.10.1
  - dash=1.16.0
  - dash-core-components=1.12.0
  - dash-html-components=1.1.1
  - dash-renderer=1.8.0
  - dash-table=4.10.1
  - dask=2.26.0
  - dask-core=2.26.0
  - dataclasses=0.7
  - decorator=4.4.2
  - defusedxml=0.6.0
  - distlib=0.3.1
  - distributed=2.26.0
  - docutils=0.15.2
  - editdistance=0.5.3
  - entrypoints=0.3
  - et_xmlfile=1.0.1
  - filelock=3.0.12
  - flake8=3.8.3
  - flask=1.1.2
  - flask-compress=1.5.0
  - flask-cors=3.0.8
  - flask-restful=0.3.8
  - freetype=2.10.2
  - fsspec=0.8.2
  - future=0.18.2
  - gensim=3.8.3
  - gitdb=4.0.5
  - gitpython=3.1.8
  - google-api-core=1.22.2
  - google-auth=1.21.2
  - google-cloud-core=1.4.1
  - google-cloud-storage=1.31.0
  - google-crc32c=1.0.0
  - google-resumable-media=1.0.0
  - googleapis-common-protos=1.51.0
  - googletrans=2.4.0
  - grpcio=1.31.0
  - heapdict=1.0.1
  - htop=3.0.2
  - identify=1.5.2
  - idna=2.10
  - imagesize=1.2.0
  - importlib-metadata=1.7.0
  - importlib_metadata=1.7.0
  - iniconfig=1.0.1
  - ipykernel=5.3.4
  - ipython=7.18.1
  - ipython-autotime=0.1
  - ipython_genutils=0.2.0
  - isort=5.5.2
  - itsdangerous=1.1.0
  - jdcal=1.4.1
  - jedi=0.17.2
  - jinja2=2.11.2
  - jmespath=0.10.0
  - joblib=0.16.0
  - jpeg=9d
  - json5=0.9.4
  - jsonschema=3.2.0
  - jupyter_client=6.1.7
  - jupyter_core=4.6.3
  - jupyterlab=2.2.8
  - jupyterlab_pygments=0.1.1
  - jupyterlab_server=1.2.0
  - kiwisolver=1.2.0
  - langdetect=1.0.7
  - lazy-object-proxy=1.4.3
  - lcms2=2.11
  - ld_impl_linux-64=2.35
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcrc32c=1.1.1
  - libffi=3.2.1
  - libgcc-ng=9.3.0
  - libgfortran-ng=7.5.0
  - libgomp=9.3.0
  - liblapack=3.8.0
  - libnl=3.2.25
  - libopenblas=0.3.10
  - libpng=1.6.37
  - libprotobuf=3.13.0
  - libsodium=1.0.18
  - libstdcxx-ng=9.3.0
  - libtiff=4.1.0
  - libwebp-base=1.1.0
  - locket=0.2.0
  - lz4-c=1.9.2
  - markupsafe=1.1.1
  - matplotlib=3.3.2
  - matplotlib-base=3.3.2
  - mccabe=0.6.1
  - mistune=0.8.4
  - more-itertools=8.5.0
  - msgpack-python=1.0.0
  - murmurhash=1.0.0
  - mypy=0.782
  - mypy_extensions=0.4.3
  - nbclient=0.5.0
  - nbconvert=6.0.3
  - nbdime=2.0.0
  - nbformat=5.0.7
  - nbstripout=0.3.9
  - ncurses=6.2
  - nest-asyncio=1.4.0
  - nltk=3.5
  - nltk_data=2019.07.04
  - nodeenv=1.5.0
  - notebook=6.1.4
  - numpy=1.19.1
  - olefile=0.46
  - openpyxl=3.0.5
  - openssl=1.1.1h
  - packaging=20.4
  - pandas=1.1.2
  - pandoc=2.10.1
  - pandocfilters=1.4.2
  - parso=0.7.1
  - partd=1.1.0
  - pathspec=0.8.0
  - patsy=0.5.1
  - pbr=5.5.0
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=7.2.0
  - pip=20.2.3
  - plac=0.9.6
  - plotly=4.10.0
  - pluggy=0.13.1
  - pre-commit=2.7.1
  - pre_commit=2.7.1
  - preshed=3.0.2
  - prometheus_client=0.8.0
  - prompt-toolkit=3.0.7
  - protobuf=3.13.0
  - psutil=5.7.2
  - ptyprocess=0.6.0
  - py=1.9.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycodestyle=2.6.0
  - pycparser=2.20
  - pydocstyle=5.1.1
  - pyflakes=2.2.0
  - pygments=2.7.0
  - pylint=2.6.0
  - pymongo=3.11.0
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - pytest=6.0.2
  - pytest-cov=2.10.1
  - python=3.8.5
  - python-dateutil=2.8.1
  - python_abi=3.8
  - pytz=2020.1
  - pyyaml=5.3.1
  - pyzmq=19.0.2
  - readline=8.0
  - recommonmark=0.6.0
  - regex=2020.7.14
  - requests=2.24.0
  - retrying=1.3.3
  - rsa=4.6
  - s3transfer=0.3.3
  - scikit-learn=0.23.2
  - scipy=1.5.2
  - seaborn=0.11.0
  - seaborn-base=0.11.0
  - send2trash=1.5.0
  - setuptools=49.6.0
  - six=1.15.0
  - smart_open=2.1.1
  - smmap=3.0.4
  - snowballstemmer=2.0.0
  - sortedcontainers=2.2.2
  - soupsieve=2.0.1
  - spacy=2.3.2
  - spacy-model-en_core_web_sm=2.3.1
  - sphinx=3.2.1
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=1.0.3
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.4
  - sqlite=3.33.0
  - srsly=1.0.2
  - statsmodels=0.12.0
  - stevedore=3.2.2
  - tblib=1.6.0
  - terminado=0.8.3
  - testpath=0.4.4
  - thinc=7.4.1
  - threadpoolctl=2.1.0
  - tk=8.6.10
  - toml=0.10.1
  - toolz=0.10.0
  - tornado=6.0.4
  - tox=3.20.0
  - tqdm=4.49.0
  - traitlets=5.0.4
  - typed-ast=1.4.1
  - typing_extensions=3.7.4.2
  - urllib3=1.25.10
  - virtualenv=20.0.20
  - wasabi=0.8.0
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - werkzeug=1.0.1
  - wheel=0.35.1
  - wrapt=1.11.2
  - xlrd=1.2.0
  - xz=5.2.5
  - yaml=0.2.5
  - yapf=0.30.0
  - zeromq=4.3.2
  - zict=2.0.0
  - zipp=3.1.0
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - argcomplete==1.12.0
    - astor==0.8.1
    - base58==2.0.1
    - blinker==1.4
    - brotli==1.0.9
    - contexttimer==0.3.3
    - dash-bootstrap-components==0.10.6
    - dash-dangerously-set-inner-html==0.0.2
    - distro==1.5.0
    - enum-compat==0.0.3
    - ipywidgets==7.5.1
    - pathtools==0.1.2
    - pipx==0.15.5.1
    - pyarrow==1.0.1
    - pydeck==0.5.0b1
    - pyenchant==3.1.1
    - streamlit==0.66.0
    - tzlocal==2.1
    - userpath==1.4.1
    - validators==0.18.1
    - watchdog==0.10.3
    - widgetsnbextension==3.5.1

