name: wb_nlp
channels:
  - judowill
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex
  - attrs
  - backcall
  - beautifulsoup4
  - blas
  - bleach
  - brotlipy
  - bs4
  - ca-certificates
  - catalogue
  - certifi
  - cffi
  - chardet
  - cryptography
  - cycler
  - cymem
  - cython-blis
  - dbus
  - decorator
  - defusedxml
  - entrypoints
  - expat
  - fontconfig
  - freetype
  - gitflow
  - glib
  - gst-plugins-base
  - gstreamer
  - icu
  - idna
  - importlib-metadata
  - importlib_metadata
  - intel-openmp
  - ipykernel
  - ipython
  - ipython_genutils
  - jedi
  - jinja2
  - joblib
  - jpeg
  - json5
  - jsonschema
  - jupyter_client
  - jupyter_core
  - jupyterlab
  - jupyterlab_server
  - kiwisolver
  - libblas
  - libcblas
  - libedit
  - libffi
  - liblapack
  - libpng
  - libsodium
  - libuuid
  - libxml2
  - markupsafe
  - matplotlib
  - matplotlib-base
  - mistune
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - murmurhash
  - nbconvert
  - nbformat
  - ncurses
  - notebook
  - numpy
  - numpy-base
  - openssl
  - packaging
  - pandoc
  - pandocfilters
  - parso
  - pcre
  - pexpect
  - pickleshare
  - pip
  - plac
  - preshed
  - prometheus_client
  - prompt-toolkit
  - ptyprocess
  - pycparser
  - pygments
  - pyopenssl
  - pyparsing
  - pyqt
  - pyrsistent
  - pyscaffold
  - pysocks
  - python
  - python-dateutil
  - python_abi
  - pytz
  - pyzmq
  - qt
  - readline
  - requests
  - scikit-learn
  - scipy
  - seaborn
  - send2trash
  - setuptools
  - sip
  - six
  - soupsieve
  - spacy
  - spacy-model-en_core_web_sm
  - sqlite
  - srsly
  - terminado
  - testpath
  - thinc
  - threadpoolctl
  - tika
  - tk
  - tornado
  - tqdm
  - traitlets
  - urllib3
  - wasabi
  - wcwidth
  - webencodings
  - wheel
  - xz
  - zeromq
  - zipp
  - zlib
  - pip:
    - alabaster
    - appdirs
    - babel
    - boto
    - boto3
    - botocore
    - cfgv
    - cmdstanpy
    - commonmark
    - cython
    - distlib
    - docutils
    - filelock
    - gensim
    - identify
    - imagesize
    - ipython-autotime
    - jmespath
    - nodeenv
    - pandas
    - pre-commit
    - pyenchant
    - pyscaffoldext-dsproject
    - pyscaffoldext-markdown
    - pyyaml
    - recommonmark
    - s3transfer
    - smart-open
    - snowballstemmer
    - sphinx
    - sphinxcontrib-applehelp
    - sphinxcontrib-devhelp
    - sphinxcontrib-htmlhelp
    - sphinxcontrib-jsmath
    - sphinxcontrib-qthelp
    - sphinxcontrib-serializinghtml
    - toml
    - tscv
    - virtualenv

