name: dev
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - bs4=4.9.1
  - ca-certificates=2020.12.8
  - certifi=2020.12.5
  - gunicorn=20.1.0
  # - graph-tool=2.37
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20191231
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libstdcxx-ng=9.1.0
  - ncurses=6.2
  - openjdk
  - openssl=1.1.1i
  - pip=20.3.3
  - python=3.8.5
  - readline=8.0
  - setuptools=51.0.0
  - spacy-model-en_core_web_sm=2.3.1
  - sqlite=3.33.0
  - tika=1.24
  - tk=8.6.10
  - wheel=0.36.2
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - aiofiles==0.6.0
    - attrs==20.3.0
    - blis==0.7.4
    - catalogue==1.0.0
    - click==7.1.2
    - cloudpickle==1.6.0
    - contexttimer==0.3.3
    - crc16==0.1.1
    - cymem==2.0.5
    - dask==2020.12.0
    - distributed==2020.12.0
    - elasticsearch==7.10.1
    # - elasticsearch-dsl==7.3.0
    - git+https://github.com/avsolatorio/elasticsearch-dsl-py.git@1f6b00bbb4be807f5334aef5801fc22b56a83781
    # - en-core-web-sm==2.3.1
    - fastapi==0.63.0
    - fasttext==0.9.2
    - flashtext==2.7
    - gensim==3.8.3
    - googletrans==3.1.0a0
    - heapdict==1.0.1
    - httptools==0.1.1
    - idna==2.10
    - iniconfig==1.1.1
    - joblib==1.0.0
    - langdetect==1.0.7
    - msgpack==1.0.2
    - murmurhash==1.0.5
    - networkx==2.5
    - nltk==3.5
    - numpy==1.19.4
    - openpyxl
    - PyICU==2.6
    - packaging==20.8
    - pandas==1.2.0
    - plac==1.1.3
    - pluggy==0.13.1
    - polyglot==16.7.4
    - preshed==3.0.5
    - psutil==5.8.0
    - py==1.10.0
    - pycld2==0.41
    - pydantic==1.7.3
    - pyenchant==3.2.0
    - pymilvus==0.3.0
    - pymongo==3.11.0
    - pyparsing==2.4.7
    - pytest==6.2.1
    - python-dateutil==2.8.1
    - python-multipart==0.0.5
    - pytz==2020.5
    - pyyaml==5.3.1
    - redis==3.5.3
    - regex==2020.11.13
    - requests==2.25.1
    - scikit-learn==0.24.0
    - scipy==1.5.4
    - six==1.15.0
    - smart-open==4.1.0
    - sortedcontainers==2.3.0
    - spacy==2.3.5
    - spacy-langdetect==0.1.2
    - srsly==1.0.5
    - starlette==0.13.6
    - tblib==1.7.0
    - thinc==7.4.5
    - threadpoolctl==2.1.0
    - toml==0.10.2
    - toolz==0.11.1
    - tornado==6.1
    - tqdm==4.55.0
    - umap-learn==0.5.1
    - urllib3==1.26.2
    - uvicorn==0.13.3
    - uvloop==0.15.2
    - wasabi==0.8.0
    - wordninja==2.0.0
    - xlrd
    - zict==2.0.0
