name: wb_nlp
channels:
  - judowill
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - attrs=19.3.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.1
  - beautifulsoup4=4.9.1
  - blas=1.0
  - bleach=3.1.5
  - bokeh=2.1.1
  - brotlipy=0.7.0
  - bs4=4.9.1
  - ca-certificates=2020.6.24
  - catalogue=1.0.0
  - certifi=2020.6.20
  - cffi=1.14.0
  - chardet=3.0.4
  - click=7.1.2
  - cloudpickle=1.5.0
  - cryptography=2.9.2
  - cycler=0.10.0
  - cymem=2.0.3
  - cython-blis=0.4.1
  - cytoolz=0.10.1
  - dask=2.20.0
  - dask-core=2.20.0
  - dbus=1.13.16
  - decorator=4.4.2
  - defusedxml=0.6.0
  - distributed=2.20.0
  - entrypoints=0.3
  - expat=2.2.9
  - fontconfig=2.13.0
  - freetype=2.10.2
  - fsspec=0.7.4
  - gitflow=0.4.1
  - glib=2.65.0
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - heapdict=1.0.1
  - icu=58.2
  - idna=2.10
  - importlib-metadata=1.7.0
  - importlib_metadata=1.7.0
  - intel-openmp=2020.1
  - ipykernel=5.3.0
  - ipython=7.16.1
  - ipython_genutils=0.2.0
  - jedi=0.17.1
  - jinja2=2.11.2
  - joblib=0.15.1
  - jpeg=9b
  - json5=0.9.5
  - jsonschema=3.2.0
  - jupyter_client=6.1.3
  - jupyter_core=4.6.3
  - jupyterlab=2.1.5
  - jupyterlab_server=1.1.5
  - kiwisolver=1.2.0
  - lcms2=2.11
  - ld_impl_linux-64=2.33.1
  - libblas=3.8.0
  - libcblas=3.8.0
  - libedit=3.1.20191231
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libgomp=9.3.0
  - liblapack=3.8.0
  - libpng=1.6.37
  - libsodium=1.0.18
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libuuid=1.0.3
  - libxcb=1.14
  - libxml2=2.9.10
  - llvm-openmp=10.0.1
  - locket=0.2.0
  - lz4-c=1.9.2
  - markupsafe=1.1.1
  - matplotlib=3.2.2
  - matplotlib-base=3.2.2
  - mistune=0.8.4
  - mkl=2020.1
  - mkl-service=2.3.0
  - mkl_fft=1.1.0
  - mkl_random=1.1.1
  - msgpack-python=1.0.0
  - murmurhash=1.0.0
  - nbconvert=5.6.1
  - nbformat=5.0.7
  - ncurses=6.2
  - notebook=6.0.3
  - numpy=1.18.5
  - numpy-base=1.18.5
  - olefile=0.46
  - openssl=1.1.1g
  - packaging=20.4
  - pandoc=2.9.2.1
  - pandocfilters=1.4.2
  - parso=0.7.0
  - partd=1.1.0
  - patsy=0.5.1
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=7.2.0
  - pip=20.1.1
  - plac=0.9.6
  - preshed=3.0.2
  - prometheus_client=0.8.0
  - prompt-toolkit=3.0.5
  - psutil=5.7.0
  - ptyprocess=0.6.0
  - pycparser=2.20
  - pygments=2.6.1
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.16.0
  - pyscaffold=3.2.3
  - pysocks=1.7.1
  - python=3.8.3
  - python-dateutil=2.8.1
  - python_abi=3.8
  - pytz=2020.1
  - pyzmq=19.0.1
  - qt=5.9.7
  - readline=8.0
  - requests=2.24.0
  - scikit-learn=0.23.1
  - scipy=1.5.0
  - seaborn=0.10.1
  - seaborn-base=0.10.1
  - send2trash=1.5.0
  - setuptools=47.3.1
  - sip=4.19.13
  - six=1.15.0
  - sortedcontainers=2.2.2
  - soupsieve=2.0.1
  - spacy=2.3.2
  - spacy-model-en_core_web_sm=2.3.0
  - sqlite=3.32.3
  - srsly=1.0.2
  - statsmodels=0.11.1
  - tblib=1.6.0
  - terminado=0.8.3
  - testpath=0.4.4
  - thinc=7.4.1
  - threadpoolctl=2.1.0
  - tika=1.24
  - tk=8.6.10
  - toolz=0.10.0
  - tornado=6.0.4
  - tqdm=4.47.0
  - traitlets=4.3.3
  - typing_extensions=3.7.4.2
  - urllib3=1.25.9
  - wasabi=0.7.0
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.34.2
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.2
  - zict=2.0.0
  - zipp=3.1.0
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - alabaster==0.7.12
    - appdirs==1.4.4
    - argcomplete==1.12.0
    - astroid==2.4.2
    - autopep8==1.5.4
    - babel==2.8.0
    - bandit==1.6.2
    - black==19.10b0
    - boto==2.49.0
    - boto3==1.14.25
    - botocore==1.17.25
    - cfgv==3.1.0
    - cmdstanpy==0.4.0
    - commonmark==0.9.1
    - cython==0.29.21
    - distlib==0.3.1
    - distro==1.5.0
    - docutils==0.15.2
    - filelock==3.0.12
    - flake8==3.8.3
    - gensim==3.8.3
    - gitdb==4.0.5
    - gitpython==3.1.7
    - identify==1.4.21
    - imagesize==1.2.0
    - iniconfig==1.0.1
    - ipython-autotime==0.1
    - isort==4.3.21
    - jmespath==0.10.0
    - lazy-object-proxy==1.4.3
    - mccabe==0.6.1
    - more-itertools==8.4.0
    - mypy==0.782
    - mypy-extensions==0.4.3
    - nodeenv==1.4.0
    - pandas==0.25.3
    - pathspec==0.8.0
    - pbr==5.4.5
    - pipx==0.15.4.0
    - pluggy==0.13.1
    - pre-commit==2.6.0
    - py==1.9.0
    - pycodestyle==2.6.0
    - pydocstyle==5.0.2
    - pyenchant==3.1.1
    - pyflakes==2.2.0
    - pylint==2.5.3
    - pyscaffoldext-dsproject==0.4
    - pyscaffoldext-markdown==0.3.2
    - pytest==6.0.1
    - pyyaml==5.3.1
    - recommonmark==0.6.0
    - regex==2020.7.14
    - s3transfer==0.3.3
    - smart-open==2.1.0
    - smmap==3.0.4
    - snowballstemmer==2.0.0
    - sphinx==3.1.2
    - sphinxcontrib-applehelp==1.0.2
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==1.0.3
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.4
    - stevedore==3.2.0
    - toml==0.10.1
    - tscv==0.0.4
    - typed-ast==1.4.1
    - userpath==1.4.1
    - virtualenv==20.0.26
    - wrapt==1.12.1
    - yapf==0.30.0

