name: prod
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - aiohttp=3.6.2
  - aniso8601=8.0.0
  - async-timeout=3.0.1
  - attrs=20.2.0
  - blas=1.0
  - boto=2.49.0
  - boto3=1.15.16
  - botocore=1.18.16
  - brotlipy=0.7.0
  - bz2file=0.98
  - c-ares=1.16.1
  - ca-certificates=2020.7.22
  - cachetools=4.1.1
  - catalogue=1.0.0
  - certifi=2020.6.20
  - cffi=1.14.3
  - chardet=3.0.4
  - click=7.1.2
  - cryptography=3.1.1
  - cycler=0.10.0
  - cymem=2.0.3
  - cython-blis=0.4.1
  - dbus=1.13.16
  - expat=2.2.10
  - flask=1.1.2
  - flask-cors=3.0.8
  - flask-restful=0.3.8
  - fontconfig=2.13.0
  - freetype=2.10.3
  - gensim=3.8.3
  - glib=2.65.0
  - google-api-core=1.22.4
  - google-auth=1.22.0
  - google-cloud-core=1.4.3
  - google-cloud-storage=1.31.2
  - google-crc32c=1.0.0
  - google-resumable-media=1.1.0
  - googleapis-common-protos=1.52.0
  - googletrans=2.4.0
  - grpcio=1.31.0
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - gunicorn=20.0.4
  - icu=58.2
  - idna=2.10
  - importlib-metadata=2.0.0
  - importlib_metadata=2.0.0
  - intel-openmp=2020.2
  - itsdangerous=1.1.0
  - jinja2=2.11.2
  - jmespath=0.10.0
  - joblib=0.17.0
  - jpeg=9b
  - jsonschema=3.0.2
  - kiwisolver=1.2.0
  - langdetect=1.0.8
  - lcms2=2.11
  - ld_impl_linux-64=2.33.1
  - libcrc32c=1.1.1
  - libedit=3.1.20191231
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libpng=1.6.37
  - libprotobuf=3.13.0.1
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libuuid=1.0.3
  - libxcb=1.14
  - libxml2=2.9.10
  - lz4-c=1.9.2
  - markupsafe=1.1.1
  - matplotlib=3.3.1
  - matplotlib-base=3.3.1
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.1.1
  - multidict=4.7.5
  - murmurhash=1.0.2
  - ncurses=6.2
  - nltk=3.5
  - nltk_data=2019.07.04
  - numpy=1.19.1
  - numpy-base=1.19.1
  - olefile=0.46
  - openssl=1.1.1h
  - pandas=1.1.3
  - pcre=8.44
  - pillow=7.2.0
  - pip=20.2.3
  - plac=0.9.6
  - preshed=3.0.2
  - protobuf=3.13.0.1
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.20
  - pymongo=3.11.0
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - python=3.8.5
  - python-dateutil=2.8.1
  - python_abi=3.8
  - pytz=2020.1
  - qt=5.9.7
  - readline=8.0
  - regex=2020.9.27
  - requests=2.24.0
  - rsa=4.6
  - s3transfer=0.3.3
  - scikit-learn=0.23.2
  - scipy=1.5.2
  - setuptools=50.3.0
  - sip=4.19.13
  - six=1.15.0
  - smart_open=3.0.0
  - spacy=2.3.2
  - sqlite=3.33.0
  - srsly=1.0.2
  - thinc=7.4.1
  - threadpoolctl=2.1.0
  - tk=8.6.10
  - tornado=6.0.4
  - tqdm=4.50.2
  - urllib3=1.25.10
  - wasabi=0.8.0
  - werkzeug=1.0.1
  - wheel=0.35.1
  - xz=5.2.5
  - yarl=1.6.0
  - zipp=3.3.0
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - contexttimer==0.3.3
    - pyenchant==3.1.1

