version: '3.6'
services:
  web:
    image: nginx:latest
    ports:
    - "80:80"
    volumes:
        - ./frontend:/frontend/nlp
        - ./site.conf:/etc/nginx/conf.d/site.conf
    links:
      - php

  php:
      image: php:7-fpm
      volumes:
        - ./frontend:/frontend/nlp

  nlp-app-mongodb:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - $BASE_DIR/$NLP_APP_MONGODB_DATADIR:/data/db
    ports:
      - $NLP_APP_MONGODB_PORT:27017
    # command: mongod --smallfiles  # --auth
    env_file:
      - .env
