
default_config:
    cleaner_config:
        # Options for cleaning.corrector.recover_segmented_words
        fix_fragmented_tokens:
            use: True
            params:
                max_len: 5
        # Expand the acronyms in the text
        expand_acronyms:
            use: True
            params: {}
        # Update the spacy doc with the whitelisted entitiy tag
        tag_whitelisted_entities:
            use: True
            params: {}
        # Use the part-of-speech as filter
        filter_by_pos:
            use: True
            params: {}
        # Use extracted entities as filter
        filter_by_entities:
            use: True
            params: {}
        # Check and fix spelling based on the Respeller module
        correct_misspelling:
            use: True
            params: {}
        # Remove stopwords from the text
        filter_stopwords:
            use: True
            params: {}

    spell_checker_config:
        __init__:
            lang: en_US
            text: null
            tokenize: null
            chunkers: null
            filters: null

    respeller_config:
        __init__:
            dictionary_file: null
            spell_threshold: 0.25
            allow_proper: True
            spell_cache: null
        infer_correct_word:
            sim_thresh: 0.0
            print_log: False
            min_len: 3
            use_suggest_score: True
        infer_correct_words:
            return_tokens_as_list: True
